dataset:
  format: json
  language: english
  name: english_qa
  path: data/english/qa_dataset.json
description: Evaluation of GPT-4 on English dataset with OpenAI embeddings
evaluation_metrics:
  generation_metrics:
  - correctness
  - relevance
  - groundedness
  - coherence
  - conciseness
  retrieval_metrics:
  - precision_at_k
  - recall_at_k
  - mrr
  - ndcg
  system_metrics:
  - latency
  - cost
experiment_name: English GPT-4 Evaluation
llm:
  api_key: null
  max_tokens: 1024
  model_name: gpt-4o
  provider: openai
  temperature: 0.0
  top_p: null
output_dir: ./results/english_gpt4
retrieval:
  chunk_overlap: 200
  chunk_size: 1000
  embedding_model: text-embedding-3-large
  filters: null
  k: 4
  retriever_type: vector
  search_type: similarity
  similarity_top_k: null
vectorstore:
  output_dir: ./vectorstores/english_qa
  path: ./vectorstores/english_qa/english_qa_cef5436db0
  source_path: data/english/qa_dataset.json
